"""empty message

Revision ID: 48589646af9b
Revises: a2d72909a5ae
Create Date: 2017-12-06 19:17:31.956415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48589646af9b'
down_revision = 'a2d72909a5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('facebook_id', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('facebook_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facebook_accounts')
    # ### end Alembic commands ###
