"""empty message

Revision ID: 717c6b500898
Revises: cc4d83e16d55
Create Date: 2017-10-31 20:29:29.015478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717c6b500898'
down_revision = 'cc4d83e16d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
