"""empty message

Revision ID: 91846e9e24d2
Revises: bd2afdaafbd2
Create Date: 2017-12-11 15:02:03.038836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91846e9e24d2'
down_revision = 'bd2afdaafbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=30), nullable=True))
    op.alter_column('users', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.alter_column('users', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
